services:
  pybot:
    build:
      context: .
      dockerfile: Dockerfile
      target: pybot
    image: pybot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./discordbot/data:/home/discordbot/data
  
  sql:
    build:
      context: .
      dockerfile: Dockerfile
      target: sqlite
    image: sqlite